### ISSUE TITLE
Toolboxes for Norm / OldNorm

### ISSUE THREAD

**Issue by vsoch** [StanfordCosyne/pancakes#1]
hey @madeleinesnyder ! Could you link me to the (source downloads) for the Norm toolboxes that you use for spm12 (and eventually spm8, although we don't need it now). To install in the container I'd like to do it from source, if at all possible.

**Comment by vsoch** [comment]
I'm using a runtime so it could also be that they come with the source, in which case I can just download that.

**Comment by menonve** [comment]
Not in Menon/software/spm12?

Sent from my iPhone

On Feb 4, 2018, at 10:15 AM, Vanessa Sochat <notifications@github.com<mailto:notifications@github.com>> wrote:


hey @madeleinesnyder<https://github.com/madeleinesnyder> ! Could you link me to the (source downloads) for the Norm toolboxes that you use for spm12 (and eventually spm8, although we don't need it now). To install in the container I'd like to do it from source, if at all possible.

**Comment by menonve** [comment]
Sure, please go ahead.

Sent from my iPhone

On Feb 4, 2018, at 10:16 AM, Vanessa Sochat <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm using a runtime so it could also be that they come with the source, in which case I can just download that.

**Comment by vsoch** [comment]
Nevermind, figured this out!

**Comment by vsoch** [comment]
Yes I'm just going to use that, but it's not ideal because it's not install from the source.

**Comment by madeleinesnyder** [comment]
Hey, is this all set? Sorry I just got back to my emails, I had to deal
with a family thing over the weekend. Also who is menonve?

**Comment by menonve** [comment]
Me.

Sent from my iPhone

On Feb 5, 2018, at 9:47 AM, Maddie Snyder <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey, is this all set? Sorry I just got back to my emails, I had to deal
with a family thing over the weekend. Also who is menonve?
